name: Regenerate the docs
on:
  schedule:
    # run a bit before midnight when go deps change
    - cron: '0 23 * * *'

  # allow manual triggering
  workflow_dispatch: {}
jobs:
  issue:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://golang:1.15
        name: Regenerate the schema docs
        env:
          GIT_TOKEN: ${{ secrets.GIT_BOT_TOKEN }}
        with:
          entrypoint: ./regen.sh